### ISSUE TITLE
How did you build the library?

### ISSUE THREAD

**Issue by andrewcz** [parsiad/QuantPDE#2]
Hi @parsiad !! amazing library! I have started learning from it.
Can you just give a general overview of how you build it -
design, where to get started etc?
Cheers

**Comment by parsiad** [comment]
Hi @andrewcz. Thanks for the kind words.

The library is not necessarily a source of good engineering practices as I wrote it when I was a student and needed it only to compute numerical solutions of various problems.

Having said that, maybe I can recommend some related reading that might inspire you:

* **C++:** Stroustrup, Bjarne. The C++ programming language. Pearson Education, 2013.
* **Linear algebra:** Saad, Yousef. Iterative methods for sparse linear systems. Society for Industrial and Applied Mathematics, 2003.
* **Optimal stochastic control theory:** Touzi, Nizar. Optimal stochastic control, stochastic target problems, and backward SDE. Vol. 29. Springer Science & Business Media, 2012.

There are also lots of books on **finite difference methods for PDEs** but I do not have a particular recommendation.

All the best!
